### ISSUE TITLE
Step has no method matching step(::DataFrameRegressionModel)

### ISSUE THREAD

**Issue by mammask** [joemliang/RegTools.jl#1]
Hello,

I am facing a couple of issues when trying to use the RegTools library in Julia. 

1) In Pkg.add("RegTools") i am getting "unkown package RegTools"

2) I used directly the scripts available at github nut I am getting: "Step has no method matching step(::DataFrameRegressionModel)".

Could you please provide assistance as I am relatively new to Julia but I have come to a dead end.

Thanks,
Kostas

**Comment by joemliang** [comment]
Hi Kostas,

Thanks for using RegTools. Regarding you questions:

1) This package is still in early stage and is not registered in METADATA. Thus you won't be able to do Pkg.add for now. 

2) Step function needs to take a RegressionModel or DataFrameRegressionModel (a sub-type of RegressionMode hence also a RegressionModel) and a direction argument. You may try step(lm1, direction="both"), where lm1 is a RegressionModel. 

I just fix a couple of things so you may clone the new scripts. 

Thank you,
Joe
